service: battleship-frontend

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:ENV}
  region: 

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ${self:service}-assets-${self:provider.stage}
      bucketPrefix: assets/
      localDir: dist/assets
      acl: public-read 
      followSymlinks: true 
      params:
        CacheControl: 'public, max-age=31536000'
            
resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-assets-${self:provider.stage}